//scr_get_input();
key_left = keyboard_check(ord('A'));
key_right = keyboard_check(ord('D'));
key_jump = keyboard_check_pressed(ord('W'));
key_down = keyboard_check_pressed(ord('S'));
left_arrow_key = keyboard_check_pressed(vk_left);
right_arrow_key = keyboard_check_pressed(vk_right);
punch_key = keyboard_check_pressed(ord("E"));
inventory_key = keyboard_check_pressed(ord('I'));
skill_key = keyboard_check_pressed(ord('P'));
